# Generated by Django 5.2 on 2025-04-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Title')),
                ('Price', models.FloatField(verbose_name='Price')),
                ('Description', models.TextField(verbose_name='Description')),
                ('Category', models.CharField(max_length=50, verbose_name='Category')),
                ('Image', models.FileField(upload_to='Product_image/', verbose_name='Image')),
            ],
        ),
    ]
